import { Tag } from "./app/shared/models/Tag";
import { Food } from "./app/shared/models/food";
export const sample_foods: Food[] = [
    {
        id: '1',
        name: 'Chicken soup',
        price: 80,
        cookTime: '40-50',
        favorite: false,
        origins: ['india'],
        stars: 3.0,
        imageUrl: 'assets/soup.jpg',
        tags: ['Soup'],
    },
    {
        id: '2',
        name: 'Chicken Noddles',
        price: 100,
        cookTime: '20-30',
        favorite: false,
        origins: ['japan'],
        stars: 4.0,
        imageUrl: 'assets/noddles.jpg',
        tags: ['Lunch'],
    },
    {
        id: '3',
        name: 'Vegitable pizza',
        price: 120,
        cookTime: '40-50',
        favorite: true,
        origins: ['italy'],
        stars: 5.0,
        imageUrl: 'assets/pizza.jpg',
        tags: ['Lunch'],
    },

    {
        id: '4',
        name: 'Vadapav',
        price: 20,
        cookTime: '10-15',
        favorite: true,
        origins: ['India'],
        stars: 5.0,
        imageUrl: 'assets/vadapav.jpg',
        tags: ['FastFood'],
    },
    {
        id: '4',
        name: 'Taco Bell',
        price: 50,
        cookTime: '20-30',
        favorite: true,
        origins: ['USA'],
        stars: 4.5,
        imageUrl: 'assets/taco.jpg',
        tags: ['FastFood'],
    },
    {
        id: '7',
        name: 'Pulms',
        price: 60,
        cookTime: '20',
        favorite: true,
        origins: ['Iran'],
        stars: 4.1,
        imageUrl: 'assets/pulms.webp',
        tags: ['SlowFood'],
    },
    {
        id: '7',
        name: 'Pine',
        price: 100,
        cookTime: '45-50',
        favorite: false,
        origins: ['Iran'],
        stars: 5.0,
        imageUrl: 'assets/pine.jpg',
        tags: ['SlowFood'],
    },
    {
        id: '1',
        name: 'Friench Fried',
        price: 120,
        cookTime: '30',
        favorite: true,
        origins: ['French'],
        stars: 5.0,
        imageUrl: 'assets/fried.jpg',
        tags: ['Fry', 'Lunch'],
    },

    {
        id: '1',
        name: 'Panner Chille',
        price: 150,
        cookTime: '30-40',
        favorite: true,
        origins: ['China'],
        stars: 4.3,
        imageUrl: 'assets/chilli.webp',
        tags: ['Dinner'],
    },
    {
        id: '1',
        name: 'Fish Fry',
        price: 180,
        cookTime: '30-40',
        favorite: true,
        origins: ['India'],
        stars: 5.0,
        imageUrl: 'assets/fish_fried.jpg',
        tags: ['Fry', 'Lunch'],
    },

]


export const sample_tags: Tag[] = [
    { name: 'All', count: 10 },
    { name: 'FastFood', count: 2 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'Dinner', count: 1 },
    { name: 'SlowFood', count: 2 },
    { name: 'Soup', count: 1 },
    { name: 'Fry', count: 2 },
]